CatCafe/config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'login' => 'login#login'
  get 'sign_up' => 'login#sign_up'

  post 'login_submit' => 'login#login_submit'
  post 'sign_up_submit' => 'login#sign_up_submit'
  post 'employee_login_submit' => 'login#employee_login_submit'

  get 'member/:id' => 'member#main', as: :member
  post 'member/:id/adopt' => 'member#adopt', as: :adopt
  post 'member/:id/adopt_submit' => 'member#adopt_submit', as: :adopt_submit

  post 'member/:id/book' => 'member#book', as: :book
  post 'member/:id/book_submit' => 'member#book_submit', as: :book_submit

  get 'employee/:id' => 'employee#main', as: :employee
  post 'employee/:id/find_transaction' => 'employee#find_transaction'
  post 'employee/:id/find_by_refId' => 'employee#find_by_refId'
  post 'employee/:id/create_transaction' => 'employee#create_transaction'
  post 'employee/:id/edit_transaction' => 'employee#edit_transaction'
  post 'employee/:id/destroy_transaction' => 'employee#destroy_transaction'
  post 'employee/:id/find_item' => 'employee#find_item'
  post 'employee/:id/create_item' => 'employee#create_item'
  post 'employee/:id/edit_item' => 'employee#edit_item'
  post 'employee/:id/destroy_item' => 'employee#destroy_item'

end

CatCafe/app/views/layouts/_footer.html.erb
<div class="container" align="center">
	<hr>
	<footer> Created by Ana, Romi, Hana, and Cheng Yu for CPSC 304 </footer>
</div>

CatCafe/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="/">CatCafé</a>
		</div>
		<ul class="nav navbar-nav">
			<li class="active"><a href="/">Home</a></li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<li><a href="<%= sign_up_path %>"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li> <!-- need to link -->
			<li><a href="<%= login_path %>"><span class="glyphicon glyphicon-log-in"></span> Login</a></li> <!-- need to link -->
		</ul>
	</div>
</nav>

CatCafe/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>CatCafé</title>
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
    <style type="text/css">
    body { background: black !important; }
    </style>
	</head>
	<body>
		<div class="container" id="app_header">
	        <%= render 'layouts/header' %>
	    </div>
	    
  		<% flash.each do |key, value| %>
    		<div class="alert alert-<%= key %>"><%= value %></div>
  		<% end %>

		<%= yield %>

		<div class="container" id="app_footer">
	        <%= render 'layouts/footer' %>
	    </div>
	</body>
</html>